// DO NOT EDIT!
// Code generated by ffjson <https://github.com/pquerna/ffjson>
// source: key.go
// DO NOT EDIT!

package jwk

import (
	"bytes"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

func (mj *Key) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if mj == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := mj.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (mj *Key) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if mj == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{ "kid":`)
	fflib.WriteJsonString(buf, string(mj.ID))
	buf.WriteString(`,"kty":`)
	fflib.WriteJsonString(buf, string(mj.Type))
	buf.WriteString(`,"alg":`)
	fflib.WriteJsonString(buf, string(mj.Algorithm))
	buf.WriteString(`,"use":`)
	fflib.WriteJsonString(buf, string(mj.Usage))
	buf.WriteByte(',')
	if len(mj.Curve) != 0 {
		buf.WriteString(`"crv":`)
		fflib.WriteJsonString(buf, string(mj.Curve))
		buf.WriteByte(',')
	}
	if len(mj.X) != 0 {
		buf.WriteString(`"x":`)
		fflib.WriteJsonString(buf, string(mj.X))
		buf.WriteByte(',')
	}
	if len(mj.Y) != 0 {
		buf.WriteString(`"y":`)
		fflib.WriteJsonString(buf, string(mj.Y))
		buf.WriteByte(',')
	}
	if len(mj.D) != 0 {
		buf.WriteString(`"d":`)
		fflib.WriteJsonString(buf, string(mj.D))
		buf.WriteByte(',')
	}
	if len(mj.N) != 0 {
		buf.WriteString(`"n":`)
		fflib.WriteJsonString(buf, string(mj.N))
		buf.WriteByte(',')
	}
	if len(mj.E) != 0 {
		buf.WriteString(`"e":`)
		fflib.WriteJsonString(buf, string(mj.E))
		buf.WriteByte(',')
	}
	if len(mj.PrimeP) != 0 {
		buf.WriteString(`"p":`)
		fflib.WriteJsonString(buf, string(mj.PrimeP))
		buf.WriteByte(',')
	}
	if len(mj.PrimeQ) != 0 {
		buf.WriteString(`"q":`)
		fflib.WriteJsonString(buf, string(mj.PrimeQ))
		buf.WriteByte(',')
	}
	if len(mj.PreDp) != 0 {
		buf.WriteString(`"dp":`)
		fflib.WriteJsonString(buf, string(mj.PreDp))
		buf.WriteByte(',')
	}
	if len(mj.PreDq) != 0 {
		buf.WriteString(`"dq":`)
		fflib.WriteJsonString(buf, string(mj.PreDq))
		buf.WriteByte(',')
	}
	if len(mj.PreQinv) != 0 {
		buf.WriteString(`"qi":`)
		fflib.WriteJsonString(buf, string(mj.PreQinv))
		buf.WriteByte(',')
	}
	if len(mj.K) != 0 {
		buf.WriteString(`"k":`)
		fflib.WriteJsonString(buf, string(mj.K))
		buf.WriteByte(',')
	}
	buf.Rewind(1)
	buf.WriteByte('}')
	return nil
}

const (
	ffj_t_Keybase = iota
	ffj_t_Keyno_such_key

	ffj_t_Key_ID

	ffj_t_Key_Type

	ffj_t_Key_Algorithm

	ffj_t_Key_Usage

	ffj_t_Key_Curve

	ffj_t_Key_X

	ffj_t_Key_Y

	ffj_t_Key_D

	ffj_t_Key_N

	ffj_t_Key_E

	ffj_t_Key_PrimeP

	ffj_t_Key_PrimeQ

	ffj_t_Key_PreDp

	ffj_t_Key_PreDq

	ffj_t_Key_PreQinv

	ffj_t_Key_K
)

var ffj_key_Key_ID = []byte("kid")

var ffj_key_Key_Type = []byte("kty")

var ffj_key_Key_Algorithm = []byte("alg")

var ffj_key_Key_Usage = []byte("use")

var ffj_key_Key_Curve = []byte("crv")

var ffj_key_Key_X = []byte("x")

var ffj_key_Key_Y = []byte("y")

var ffj_key_Key_D = []byte("d")

var ffj_key_Key_N = []byte("n")

var ffj_key_Key_E = []byte("e")

var ffj_key_Key_PrimeP = []byte("p")

var ffj_key_Key_PrimeQ = []byte("q")

var ffj_key_Key_PreDp = []byte("dp")

var ffj_key_Key_PreDq = []byte("dq")

var ffj_key_Key_PreQinv = []byte("qi")

var ffj_key_Key_K = []byte("k")

func (uj *Key) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return uj.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

func (uj *Key) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error = nil
	currentKey := ffj_t_Keybase
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit. woo.
			if tok == fflib.FFTok_right_bracket {
				goto done
			}
			if tok != fflib.FFTok_string {
				wantedTok = fflib.FFTok_string
				goto wrongtokenerror
			}

			kn := fs.Output.Bytes()
			if len(kn) <= 0 {
				// "" case. hrm.
				currentKey = ffj_t_Keyno_such_key
				state = fflib.FFParse_want_colon
				goto mainparse
			} else {
				switch kn[0] {

				case 'a':

					if bytes.Equal(ffj_key_Key_Algorithm, kn) {
						currentKey = ffj_t_Key_Algorithm
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'c':

					if bytes.Equal(ffj_key_Key_Curve, kn) {
						currentKey = ffj_t_Key_Curve
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'd':

					if bytes.Equal(ffj_key_Key_D, kn) {
						currentKey = ffj_t_Key_D
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Key_PreDp, kn) {
						currentKey = ffj_t_Key_PreDp
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Key_PreDq, kn) {
						currentKey = ffj_t_Key_PreDq
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'e':

					if bytes.Equal(ffj_key_Key_E, kn) {
						currentKey = ffj_t_Key_E
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'k':

					if bytes.Equal(ffj_key_Key_ID, kn) {
						currentKey = ffj_t_Key_ID
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Key_Type, kn) {
						currentKey = ffj_t_Key_Type
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Key_K, kn) {
						currentKey = ffj_t_Key_K
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'n':

					if bytes.Equal(ffj_key_Key_N, kn) {
						currentKey = ffj_t_Key_N
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'p':

					if bytes.Equal(ffj_key_Key_PrimeP, kn) {
						currentKey = ffj_t_Key_PrimeP
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'q':

					if bytes.Equal(ffj_key_Key_PrimeQ, kn) {
						currentKey = ffj_t_Key_PrimeQ
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffj_key_Key_PreQinv, kn) {
						currentKey = ffj_t_Key_PreQinv
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'u':

					if bytes.Equal(ffj_key_Key_Usage, kn) {
						currentKey = ffj_t_Key_Usage
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'x':

					if bytes.Equal(ffj_key_Key_X, kn) {
						currentKey = ffj_t_Key_X
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'y':

					if bytes.Equal(ffj_key_Key_Y, kn) {
						currentKey = ffj_t_Key_Y
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				}

				if fflib.EqualFoldRight(ffj_key_Key_K, kn) {
					currentKey = ffj_t_Key_K
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Key_PreQinv, kn) {
					currentKey = ffj_t_Key_PreQinv
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Key_PreDq, kn) {
					currentKey = ffj_t_Key_PreDq
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Key_PreDp, kn) {
					currentKey = ffj_t_Key_PreDp
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Key_PrimeQ, kn) {
					currentKey = ffj_t_Key_PrimeQ
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Key_PrimeP, kn) {
					currentKey = ffj_t_Key_PrimeP
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Key_E, kn) {
					currentKey = ffj_t_Key_E
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Key_N, kn) {
					currentKey = ffj_t_Key_N
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Key_D, kn) {
					currentKey = ffj_t_Key_D
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Key_Y, kn) {
					currentKey = ffj_t_Key_Y
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Key_X, kn) {
					currentKey = ffj_t_Key_X
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Key_Curve, kn) {
					currentKey = ffj_t_Key_Curve
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_Key_Usage, kn) {
					currentKey = ffj_t_Key_Usage
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffj_key_Key_Algorithm, kn) {
					currentKey = ffj_t_Key_Algorithm
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_Key_Type, kn) {
					currentKey = ffj_t_Key_Type
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffj_key_Key_ID, kn) {
					currentKey = ffj_t_Key_ID
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				currentKey = ffj_t_Keyno_such_key
				state = fflib.FFParse_want_colon
				goto mainparse
			}

		case fflib.FFParse_want_colon:
			if tok != fflib.FFTok_colon {
				wantedTok = fflib.FFTok_colon
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_value
			continue
		case fflib.FFParse_want_value:

			if tok == fflib.FFTok_left_brace || tok == fflib.FFTok_left_bracket || tok == fflib.FFTok_integer || tok == fflib.FFTok_double || tok == fflib.FFTok_string || tok == fflib.FFTok_bool || tok == fflib.FFTok_null {
				switch currentKey {

				case ffj_t_Key_ID:
					goto handle_ID

				case ffj_t_Key_Type:
					goto handle_Type

				case ffj_t_Key_Algorithm:
					goto handle_Algorithm

				case ffj_t_Key_Usage:
					goto handle_Usage

				case ffj_t_Key_Curve:
					goto handle_Curve

				case ffj_t_Key_X:
					goto handle_X

				case ffj_t_Key_Y:
					goto handle_Y

				case ffj_t_Key_D:
					goto handle_D

				case ffj_t_Key_N:
					goto handle_N

				case ffj_t_Key_E:
					goto handle_E

				case ffj_t_Key_PrimeP:
					goto handle_PrimeP

				case ffj_t_Key_PrimeQ:
					goto handle_PrimeQ

				case ffj_t_Key_PreDp:
					goto handle_PreDp

				case ffj_t_Key_PreDq:
					goto handle_PreDq

				case ffj_t_Key_PreQinv:
					goto handle_PreQinv

				case ffj_t_Key_K:
					goto handle_K

				case ffj_t_Keyno_such_key:
					err = fs.SkipField(tok)
					if err != nil {
						return fs.WrapErr(err)
					}
					state = fflib.FFParse_after_value
					goto mainparse
				}
			} else {
				goto wantedvalue
			}
		}
	}

handle_ID:

	/* handler: uj.ID type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.ID = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Type:

	/* handler: uj.Type type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.Type = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Algorithm:

	/* handler: uj.Algorithm type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.Algorithm = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Usage:

	/* handler: uj.Usage type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.Usage = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Curve:

	/* handler: uj.Curve type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.Curve = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_X:

	/* handler: uj.X type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.X = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Y:

	/* handler: uj.Y type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.Y = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_D:

	/* handler: uj.D type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.D = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_N:

	/* handler: uj.N type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.N = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_E:

	/* handler: uj.E type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.E = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_PrimeP:

	/* handler: uj.PrimeP type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.PrimeP = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_PrimeQ:

	/* handler: uj.PrimeQ type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.PrimeQ = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_PreDp:

	/* handler: uj.PreDp type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.PreDp = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_PreDq:

	/* handler: uj.PreDq type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.PreDq = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_PreQinv:

	/* handler: uj.PreQinv type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.PreQinv = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_K:

	/* handler: uj.K type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			uj.K = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

wantedvalue:
	return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
wrongtokenerror:
	return fs.WrapErr(fmt.Errorf("ffjson: wanted token: %v, but got token: %v output=%s", wantedTok, tok, fs.Output.String()))
tokerror:
	if fs.BigError != nil {
		return fs.WrapErr(fs.BigError)
	}
	err = fs.Error.ToError()
	if err != nil {
		return fs.WrapErr(err)
	}
	panic("ffjson-generated: unreachable, please report bug.")
done:
	return nil
}

func (mj *Set) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if mj == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := mj.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (mj *Set) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if mj == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{"keys":`)
	if mj.Keys != nil {
		buf.WriteString(`[`)
		for i, v := range mj.Keys {
			if i != 0 {
				buf.WriteString(`,`)
			}

			{

				err = v.MarshalJSONBuf(buf)
				if err != nil {
					return err
				}

			}
		}
		buf.WriteString(`]`)
	} else {
		buf.WriteString(`null`)
	}
	buf.WriteByte('}')
	return nil
}

const (
	ffj_t_Setbase = iota
	ffj_t_Setno_such_key

	ffj_t_Set_Keys
)

var ffj_key_Set_Keys = []byte("keys")

func (uj *Set) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return uj.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

func (uj *Set) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error = nil
	currentKey := ffj_t_Setbase
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit. woo.
			if tok == fflib.FFTok_right_bracket {
				goto done
			}
			if tok != fflib.FFTok_string {
				wantedTok = fflib.FFTok_string
				goto wrongtokenerror
			}

			kn := fs.Output.Bytes()
			if len(kn) <= 0 {
				// "" case. hrm.
				currentKey = ffj_t_Setno_such_key
				state = fflib.FFParse_want_colon
				goto mainparse
			} else {
				switch kn[0] {

				case 'k':

					if bytes.Equal(ffj_key_Set_Keys, kn) {
						currentKey = ffj_t_Set_Keys
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				}

				if fflib.EqualFoldRight(ffj_key_Set_Keys, kn) {
					currentKey = ffj_t_Set_Keys
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				currentKey = ffj_t_Setno_such_key
				state = fflib.FFParse_want_colon
				goto mainparse
			}

		case fflib.FFParse_want_colon:
			if tok != fflib.FFTok_colon {
				wantedTok = fflib.FFTok_colon
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_value
			continue
		case fflib.FFParse_want_value:

			if tok == fflib.FFTok_left_brace || tok == fflib.FFTok_left_bracket || tok == fflib.FFTok_integer || tok == fflib.FFTok_double || tok == fflib.FFTok_string || tok == fflib.FFTok_bool || tok == fflib.FFTok_null {
				switch currentKey {

				case ffj_t_Set_Keys:
					goto handle_Keys

				case ffj_t_Setno_such_key:
					err = fs.SkipField(tok)
					if err != nil {
						return fs.WrapErr(err)
					}
					state = fflib.FFParse_after_value
					goto mainparse
				}
			} else {
				goto wantedvalue
			}
		}
	}

handle_Keys:

	/* handler: uj.Keys type=[]jwk.Key kind=slice quoted=false*/

	{

		{
			if tok != fflib.FFTok_left_brace && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for ", tok))
			}
		}

		if tok == fflib.FFTok_null {
			uj.Keys = nil
		} else {

			uj.Keys = make([]Key, 0)

			wantVal := true

			for {

				var v Key

				tok = fs.Scan()
				if tok == fflib.FFTok_error {
					goto tokerror
				}
				if tok == fflib.FFTok_right_brace {
					break
				}

				if tok == fflib.FFTok_comma {
					if wantVal == true {
						// TODO(pquerna): this isn't an ideal error message, this handles
						// things like [,,,] as an array value.
						return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
					}
					continue
				} else {
					wantVal = true
				}

				/* handler: v type=jwk.Key kind=struct quoted=false*/

				{
					if tok == fflib.FFTok_null {

						state = fflib.FFParse_after_value
						goto mainparse
					}

					err = v.UnmarshalJSONFFLexer(fs, fflib.FFParse_want_key)
					if err != nil {
						return err
					}
					state = fflib.FFParse_after_value
				}

				uj.Keys = append(uj.Keys, v)
				wantVal = false
			}
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

wantedvalue:
	return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
wrongtokenerror:
	return fs.WrapErr(fmt.Errorf("ffjson: wanted token: %v, but got token: %v output=%s", wantedTok, tok, fs.Output.String()))
tokerror:
	if fs.BigError != nil {
		return fs.WrapErr(fs.BigError)
	}
	err = fs.Error.ToError()
	if err != nil {
		return fs.WrapErr(err)
	}
	panic("ffjson-generated: unreachable, please report bug.")
done:
	return nil
}
